[theme]
# 基础主题设置
base = "dark"
primaryColor = "#4CAF50"  # [主题基础色] 翠绿色 Forest Green - 用于主要强调和交互元素

# 主要背景色设置
backgroundColor = "#1E1E1E"  # [主页面背景] 深炭黑 Dark Charcoal - 用于整体页面背景
secondaryBackgroundColor = "#252526"  # [次要页面背景] 石墨黑 Graphite Black - 用于卡片、面板背景
tertiaryBackgroundColor = "#2D2D2D"  # [第三级背景] 烟灰黑 Smoke Black - 用于嵌套元素背景

# 主要文字颜色
textColor = "#FFFFFF"  # [主要文字] 纯白色 Pure White - 用于主要文本内容
secondaryTextColor = "#B0B0B0"  # [次要文字] 浅灰色 Light Gray - 用于次要文本信息
tertiaryTextColor = "#808080"  # [第三级文字] 中灰色 Medium Gray - 用于辅助性文本

# 侧边栏设置
sidebarBackgroundColor = "#252526"  # [侧边栏背景] 石墨黑 Graphite Black - 侧边栏整体背景色
sidebarTextColor = "#FFFFFF"  # [侧边栏文字] 纯白色 Pure White - 侧边栏普通文本颜色
sidebarTitleColor = "#4CAF50"  # [侧边栏标题] 翠绿色 Forest Green - 侧边栏主标题颜色
sidebarSubtitleColor = "#B0B0B0"  # [侧边栏副标题] 浅灰色 Light Gray - 侧边栏副标题颜色
sidebarLinkColor = "#4CAF50"  # [侧边栏链接] 翠绿色 Forest Green - 侧边栏链接常态颜色
sidebarLinkHoverColor = "#66BB6A"  # [侧边栏链接悬停] 薄荷绿 Mint Green - 侧边栏链接悬停颜色

# 组件颜色
buttonColor = "#4CAF50"  # [按钮背景] 翠绿色 Forest Green - 按钮常态背景色
buttonTextColor = "#FFFFFF"  # [按钮文字] 纯白色 Pure White - 按钮文字颜色
buttonHoverColor = "#66BB6A"  # [按钮悬停背景] 薄荷绿 Mint Green - 按钮悬停时背景色
buttonHoverTextColor = "#FFFFFF"  # [按钮悬停文字] 纯白色 Pure White - 按钮悬停时文字颜色

# 输入组件
inputBackgroundColor = "#3D3D3D"  # [输入框背景] 深灰色 Dark Gray - 输入框背景色
inputTextColor = "#FFFFFF"  # [输入框文字] 纯白色 Pure White - 输入框文字颜色
inputBorderColor = "#555555"  # [输入框边框] 中深灰色 Medium Dark Gray - 输入框边框颜色
inputPlaceholderColor = "#808080"  # [输入框占位符] 中灰色 Medium Gray - 输入框占位符颜色

# 选择器组件
selectBackgroundColor = "#3D3D3D"  # [选择器背景] 深灰色 Dark Gray - 下拉选择器背景色
selectTextColor = "#FFFFFF"  # [选择器文字] 纯白色 Pure White - 下拉选择器文字颜色
selectBorderColor = "#555555"  # [选择器边框] 中深灰色 Medium Dark Gray - 下拉选择器边框颜色

# 状态颜色
successColor = "#4CAF50"  # [成功状态] 翠绿色 Forest Green - 用于成功提示和状态
warningColor = "#FFA726"  # [警告状态] 橙色 Orange - 用于警告提示和状态
errorColor = "#EF5350"  # [错误状态] 红色 Red - 用于错误提示和状态
infoColor = "#42A5F5"  # [信息状态] 天蓝色 Sky Blue - 用于一般信息提示

# 链接颜色
linkColor = "#4CAF50"  # [链接常态] 翠绿色 Forest Green - 普通链接颜色
linkHoverColor = "#66BB6A"  # [链接悬停] 薄荷绿 Mint Green - 链接悬停时颜色

# 表格样式
tableBackgroundColor = "#2D2D2D"  # [表格背景] 烟灰黑 Smoke Black - 表格整体背景色
tableHeaderBackgroundColor = "#3D3D3D"  # [表头背景] 深灰色 Dark Gray - 表格头部背景色
tableHeaderTextColor = "#FFFFFF"  # [表头文字] 纯白色 Pure White - 表格头部文字颜色
tableBorderColor = "#555555"  # [表格边框] 中深灰色 Medium Dark Gray - 表格边框颜色

# 阴影设置
shadowColor = "rgba(0, 0, 0, 0.3)"  # [阴影颜色] 半透明黑色 Semi-transparent Black - 用于元素阴影
shadowSize = "0 2px 5px"  # [阴影大小] 阴影尺寸设置 Shadow Size

# 布局设置
borderRadius = "4px"  # [圆角] 边框圆角半径 Border Radius
borderWidth = "1px"  # [边框] 标准边框宽度 Border Width
spacing = "1rem"  # [间距] 基础元素间距 Base Spacing
widgetSpacing = "0.5rem"  # [组件间距] 组件内部间距 Widget Spacing
sidebarWidth = "300px"  # [侧边栏宽度] 侧边栏宽度设置 Sidebar Width

# 字体设置
font = "sans serif"  # [主字体] 无衬线字体 Sans Serif
fontSize = "16px"  # [字体大小] 标准字体大小 Standard Font Size
headingFont = "sans serif"  # [标题字体] 无衬线字体 Sans Serif
headingFontSize = "24px"  # [标题大小] 标题字体大小 Heading Font Size
subtitleFontSize = "14px"  # [副标题大小] 副标题字体大小 Subtitle Font Size

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
level = "info"

[client]
toolbarMode = "auto"
caching = true

[runner]
magicEnabled = true
installTracer = false

[global]
developmentMode = false
showDocString = true
