[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"

[theme]
# 深色主题设置
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
# 添加运行器配置
magicEnabled = true
installTracer = true
fastReruns = true