[server]
headless = false
port = 8501
enableCORS = true
enableXsrfProtection = true

[theme]
# 深色主题设置
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false